//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.PatientMeasurement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalDatabase : DbContext
    {
        public HospitalDatabase()
            : base("name=HospitalDatabase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<EmployeePatientDepartments> EmployeePatientDepartments { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<JobTypes> JobTypes { get; set; }
        public virtual DbSet<Measurements> Measurements { get; set; }
        public virtual DbSet<MeasurementTypes> MeasurementTypes { get; set; }
        public virtual DbSet<Patients> Patients { get; set; }
        public virtual DbSet<Thesises> Thesises { get; set; }
    }
}
