//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.PatientMeasurement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePatientDepartments
    {
        public System.Guid EmployeePatientDepartmentID { get; set; }
        public System.Guid EmployeeID { get; set; }
        public System.Guid PatientID { get; set; }
        public System.Guid DepartmentID { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
